@RinhaBackend.Api_HostAddress = http://localhost:8080

POST  http://localhost:7624/todos/
Accept: application/json
Content-Type: application/json

{
    "title": "Learn HTTP",
    "description": "Understand how to use HTTP methods and status codes",
    "completed": false
}

###
