@RinhaBackend.Api_HostAddress = http://localhost:8080

POST  http://localhost:9999/payments/
Accept: application/json
Content-Type: application/json

{
  "correlationId": "4a7901b8-7d26-4d9d-aa19-4dc1c7cf6014",
  "amount": 19.90
}

###

GET http://localhost:9999/payments-summary
Accept: application/json

###
