services:
  rinhabackend.api:
    image: rinhabackend.api
    depends_on:
      - rabbitmq
    platform: "linux/amd64"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    networks:
      - backend
    build:
      context: .
      dockerfile: RinhaBackend.Api/Dockerfile
    ports:
      - "7623:8080"

  rinhabackend.worker:
    image: rinhabackend.worker
    platform: "linux/amd64"
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"
    networks:
      - backend
    build:
      context: .
      dockerfile: RinhaBackend.Worker/Dockerfile
        
  rabbitmq:
    image: rabbitmq:3-management
    platform: "linux/amd64"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
    networks:
      - backend
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  backend:
    # Specify driver options
    driver: bridge