services:      
  nginx:
    image: nginx-loadbalancer
    platform: "linux/amd64"
    depends_on:
      - rinhabackend.api1
      - rinhabackend.api2
#    deploy:
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: "10MB"
    networks:
      - frontdoor
      - backend
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    ports:
      - "9999:80"

  rinhabackend.api1:
    image: rinhabackend.api
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "0.1"
    #          memory: "10MB"
    networks:
      - backend
    build:
      context: .
      dockerfile: RinhaBackend.Api/Dockerfile

  rinhabackend.api2:
    image: rinhabackend.api
    platform: "linux/amd64"
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "0.1"
    #          memory: "10MB"
    networks:
      - backend
    build:
      context: .
      dockerfile: RinhaBackend.Api/Dockerfile
      
  rinhabackend.worker:
    image: rinhabackend.worker
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "0.1"
    #          memory: "10MB"
    networks:
      - backend
      - payment-processor
    build:
      context: .
      dockerfile: RinhaBackend.Worker/Dockerfile

networks:
  frontdoor:
    # Specify driver options
    driver: bridge
  backend:
    # Specify driver options
    driver: bridge
  payment-processor:
      external: true

