# This is a generated file. Not intended for manual editing.
services:
  rinhabackend.api1:
    build:
      context: "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend"
      dockerfile: "RinhaBackend.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/RinhaBackend.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "rinhabackend.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend\\RinhaBackend.Api:/app:rw"
    - "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend:/src:rw"
    - "C:\\Users\\maiaa\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  rinhabackend.api2:
    build:
      context: "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend"
      dockerfile: "RinhaBackend.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/RinhaBackend.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "rinhabackend.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend\\RinhaBackend.Api:/app:rw"
    - "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend:/src:rw"
    - "C:\\Users\\maiaa\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  rinhabackend.worker:
    build:
      context: "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend"
      dockerfile: "RinhaBackend.Worker/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/RinhaBackend.Worker.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "rinhabackend.worker:dev"
    ports: []
    volumes:
    - "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend\\RinhaBackend.Worker:/app:rw"
    - "C:\\Users\\maiaa\\Documents\\Dev\\personal\\rinha_backend:/src:rw"
    - "C:\\Users\\maiaa\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
